version: "3.8"

# 定义网络：local_net
networks:
  local_net:
    name: local_net

# 定义服务
services:
  # es7服务
  es7:
    image: elasticsearch:7.17.5
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - local_net
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - discovery.type=single-node

  # skywalking-oap-server服务
  skywalking-oap-server:
    image: apache/skywalking-oap-server:8.9.1
    ports:
      - 11800:11800
      - 12800:12800
    networks:
      - local_net
    depends_on:
      es7:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "/skywalking/bin/swctl ch" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - SW_STORAGE=elasticsearch
      - SW_STORAGE_ES_CLUSTER_NODES=es7:9200

  # skywalking-ui服务
  skywalking-ui:
    image: apache/skywalking-ui:8.9.1
    ports:
      - 18080:8080
    networks:
      - local_net
    depends_on:
      - skywalking-oap-server
    environment:
      - SW_OAP_ADDRESS=http://skywalking-oap-server:12800

  # 示例项目服务
  spring-boot-monitoring-skywalking:
    image: local_test/spring-boot-monitoring-skywalking:1.0.0-SNAPSHOT
    ports:
        - 8080:8080
    networks:
      - local_net
    depends_on:
      skywalking-oap-server:
        condition: service_healthy